apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "600Mi"
            cpu: "500m"
          requests:
            memory: "50Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      
        