apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx1
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name:  nginx2
    image:  nginx
    imagePullPolicy: IfNotPresent
    resources:
        limits:
          memory : "200Mi"
          cpu : "500m"
    ports:
      - containerPort: 80
    restartPolicy: Never

