# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  NodeCount = 1
  MasterCount = 1

  (1..NodeCount).each do |i|
    config.vm.define "worker#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "worker#{i}.example.com"
      node.vm.network "private_network", ip: "172.42.42.10#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "worker#{i}"
        v.memory = 2048
        v.cpus = 1
      end
    end
  end

  (1..MasterCount).each do |i|
    config.vm.define "master#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "master#{i}.example.com"
      node.vm.network "private_network", ip: "172.42.42.20#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "master#{i}"
        v.memory = 2048
        v.cpus = 2
      end
    end
  end

end
