# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    # protocol: udp # Optional, defaults to tcp
  - containerPort: 8080
    hostPort: 8080
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    # protocol: udp
  - containerPort: 8081
    hostPort: 8081
    listenAddress: "0.0.0.0" 
  - containerPort: 8082
    hostPort: 8082
    listenAddress: "0.0.0.0" 
  - containerPort: 8083
    hostPort: 8083
    listenAddress: "0.0.0.0" 
  - containerPort: 8084
    hostPort: 8084
    listenAddress: "0.0.0.0" 
- role: worker
- role: worker
# - role: worker